name: Create Release

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build-and-release:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Elixir and Erlang
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.18.2'  # Adjust to your version
        otp-version: '27.0'       # Adjust to your version

    - name: Install dependencies
      run: mix deps.get

    - name: Build escript
      run: mix escript.build

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name || github.run_number }}
        release_name: Release ${{ github.ref_name || github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload escript binary to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./todo      # Change this to your escript filename
        asset_name: todo         # The name for the uploaded artifact
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
